//! The `modifiers` / `economy` ORACLE document (`roblox/test/modifiers_test.luau`).
//!
//! `roblox/test/modifiers_test.luau` asserts the Luau port of `Modifiers.luau` +
//! `Economy.luau` against a document of expected values. Every one of those values
//! is produced HERE, by running the real Rust — never hand-derived
//! (`roblox/CONTRACTS.md` C4, `roblox/SIM-SPEC.md` §S1).
//!
//! ## Why this lives inside the lib
//!
//! The document used to be generated by a throwaway crate outside the repo taking a
//! path dependency on `sim`. That worked for the parts reachable through `pub` API —
//! `Modifiers::{apply_effect, damage_mult, …}` — and *could not* work for the rest:
//! `modifiers::apply_ramps` and every `economy::*` entry point are `pub(crate)`, so
//! an external crate cannot call them at all. Those two arrays were therefore
//! "carried forward verbatim" from an older pass and went stale the moment the
//! balance changed underneath them.
//!
//! Putting the generator in the lib fixes that without widening a single item's
//! visibility: a module inside `sim` may call `pub(crate)` items directly. The whole
//! document is regenerable from one command and "carried forward verbatim" no longer
//! exists.
//!
//! ## Invariants
//!
//! - **Every expected value comes out of running the Rust.** Nothing below writes an
//!   expectation by hand; the tables here are the case *inputs* only.
//! - **Deterministic**: no wall-clock, no `HashMap` iteration, no platform RNG. The
//!   only RNG is the arena's own seeded `rng_proc`, driven from a fixed seed per case.
//! - No floats: every `Fixed` is emitted as its 16-digit two's-complement raw, so a
//!   divergence in the port is a bit-level divergence rather than an "about right".
//! - Case NAMES and case ORDER are part of the contract — the Luau tags every
//!   assertion with them. Add cases; do not reorder or rename them.

use super::json::{int, ints, obj, Value};
use super::{hex, hex_u, words};
use crate::content::{self as c, ModEffect as E};
use crate::economy;
use crate::modifiers;
use crate::state::{ActiveRamp, ArenaState, Economy, Modifiers, Tank, WeaponInstance};
use crate::EntityId;
use determinism::Fixed;

/// Schema version of the emitted document. Bump only alongside the Luau reader.
const SCHEMA_VERSION: i64 = 1;

// ===================== state serializers =====================

fn tank_value(t: &Tank) -> Value {
    obj(vec![
        ("hp", int(t.hp)),
        ("max_hp", int(t.max_hp)),
        ("armor", int(t.armor)),
        ("dodge_num", int(t.dodge_num as i64)),
        ("dodge_den", int(t.dodge_den as i64)),
        ("mana_shield", int(t.mana_shield)),
        ("mana_shield_max", int(t.mana_shield_max)),
        ("mana_regen_per_tick", int(t.mana_regen_per_tick)),
        ("hp_regen_per_tick", int(t.hp_regen_per_tick)),
        ("spikes_damage", int(t.spikes_damage)),
        ("spikes_mult", hex(t.spikes_mult.raw())),
        ("shield_active_dr", hex(t.shield_active_dr.raw())),
        ("heal_on_damaged", int(t.heal_on_damaged)),
        ("heal_on_kill", int(t.heal_on_kill)),
        ("mana_on_kill", int(t.mana_on_kill)),
        ("heal_on_poison", int(t.heal_on_poison)),
        ("healing_mult", hex(t.healing_mult.raw())),
        ("missing_hp_heal_pct", hex(t.missing_hp_heal_pct.raw())),
        ("revives", int(t.revives as i64)),
        ("revive_bonus_hp", int(t.revive_bonus_hp)),
        ("shieldbreak_stun_range", int(t.shieldbreak_stun_range)),
        ("shieldbreak_stun_ticks", int(t.shieldbreak_stun_ticks as i64)),
        ("spikes_poison_dps", int(t.spikes_poison_dps)),
        ("spikes_poison_ticks", int(t.spikes_poison_ticks as i64)),
        ("spikes_stack_per", int(t.spikes_stack_per)),
        ("spikes_stacks", int(t.spikes_stacks as i64)),
        ("spikes_stacks_max", int(t.spikes_stacks_max as i64)),
        ("aura_range", int(t.aura_range)),
        ("aura_cadence", int(t.aura_cadence as i64)),
        ("aura_damage", int(t.aura_damage)),
        ("aura_poison_dps", int(t.aura_poison_dps)),
        ("aura_poison_ticks", int(t.aura_poison_ticks as i64)),
        ("aura_tick", int(t.aura_tick as i64)),
    ])
}

fn economy_value(e: &Economy) -> Value {
    obj(vec![
        ("gold", int(e.gold)),
        ("income_per_tick", int(e.income_per_tick)),
        ("income_mult", hex(e.income_mult.raw())),
        ("income_regen_pct", hex(e.income_regen_pct.raw())),
        ("bounty_mult", hex(e.bounty_mult.raw())),
        ("bounty_proc_chance_pct", int(e.bounty_proc_chance_pct)),
        ("bounty_proc_bonus", hex(e.bounty_proc_bonus.raw())),
        ("gold_per_damage", hex(e.gold_per_damage.raw())),
        ("income_shield_pct", hex(e.income_shield_pct.raw())),
    ])
}

fn modifiers_value(m: &Modifiers) -> Value {
    obj(vec![
        ("add_global", hex(m.add_global.raw())),
        ("add_by_type", Value::Arr(m.add_by_type.iter().map(|f| hex(f.raw())).collect())),
        ("add_by_scope", Value::Arr(m.add_by_scope.iter().map(|f| hex(f.raw())).collect())),
        ("mul_global", hex(m.mul_global.raw())),
        ("attack_speed", hex(m.attack_speed.raw())),
        ("vs_stunned", hex(m.vs_stunned.raw())),
        ("vs_poisoned", hex(m.vs_poisoned.raw())),
        ("poison_dmg_mult", hex(m.poison_dmg_mult.raw())),
        ("stun_dur_mult", hex(m.stun_dur_mult.raw())),
        (
            "weapon_count_scaling",
            Value::Arr(
                m.weapon_count_scaling
                    .iter()
                    .map(|r| {
                        obj(vec![
                            ("weapon_def", int(r.weapon_def as i64)),
                            ("dmg_type", int(r.dmg_type as i64)),
                            ("per", hex(r.per.raw())),
                        ])
                    })
                    .collect(),
            ),
        ),
        ("dmg_per_maxhp_rate", hex(m.dmg_per_maxhp_rate.raw())),
        ("dmg_per_bounty_rate", hex(m.dmg_per_bounty_rate.raw())),
        ("shield_active_dmg", hex(m.shield_active_dmg.raw())),
    ])
}

// ===================== case setup =====================

/// Force a pre-state field so the clamps / ceilings / overheal paths are
/// reachable. Mirrors the `SETUP` table in `modifiers_test.luau` key for key; an
/// unknown key is a loud panic rather than a silently skipped case.
fn apply_setup(s: &mut ArenaState, key: &str, v: i64) {
    match key {
        "gold" => s.economy.gold = v,
        "income_per_tick" => s.economy.income_per_tick = v,
        "bounty_proc_chance_pct" => s.economy.bounty_proc_chance_pct = v,
        "hp" => s.tank.hp = v,
        "max_hp" => s.tank.max_hp = v,
        "armor" => s.tank.armor = v,
        "mana_shield" => s.tank.mana_shield = v,
        "mana_shield_max" => s.tank.mana_shield_max = v,
        "heal_on_kill" => s.tank.heal_on_kill = v,
        "mana_on_kill" => s.tank.mana_on_kill = v,
        "revives" => s.tank.revives = v as u32,
        "revive_bonus_hp" => s.tank.revive_bonus_hp = v,
        "hp_regen_per_tick" => s.tank.hp_regen_per_tick = v,
        "mana_regen_per_tick" => s.tank.mana_regen_per_tick = v,
        "dodge_den" => s.tank.dodge_den = v as u32,
        "aura_cadence" => s.tank.aura_cadence = v as u32,
        "tick" => s.tick = v as u32,
        "dead" => s.dead = v != 0,
        other => panic!("oracle: unknown setup key {other:?}"),
    }
}

/// `Fixed`-valued twin of [`apply_setup`] (the `FIXED_SETUP` table in the Luau).
fn apply_fixed_setup(s: &mut ArenaState, key: &str, v: Fixed) {
    match key {
        "income_mult" => s.economy.income_mult = v,
        "income_regen_pct" => s.economy.income_regen_pct = v,
        "income_shield_pct" => s.economy.income_shield_pct = v,
        "bounty_mult" => s.economy.bounty_mult = v,
        "bounty_proc_bonus" => s.economy.bounty_proc_bonus = v,
        "healing_mult" => s.tank.healing_mult = v,
        other => panic!("oracle: unknown fixed setup key {other:?}"),
    }
}

fn arsenal(defs: &[u16]) -> Vec<WeaponInstance> {
    defs.iter()
        .map(|&def| WeaponInstance { instance_id: EntityId(0), def, next_fire_tick: 0 })
        .collect()
}

/// `n` copies of one effect — the deep multiplicative / bundle stacks below are
/// long enough that spelling them out would bury the table.
fn rep(e: E, n: usize) -> Vec<E> {
    vec![e; n]
}

/// `n` repetitions of the `[+2000 flat Max HP, +25% Max HP]` purchase bundle: the
/// stack that drives the `SOFT^3 / mag^3` intermediate past 2^53, where a port that
/// lets it land in a raw Luau number goes silently wrong.
fn maxhp_bundle(n: usize) -> Vec<E> {
    let mut v = Vec::with_capacity(n * 2);
    for _ in 0..n {
        v.push(E::MaxHp(2000));
        v.push(E::MaxHpPct(25, 100));
    }
    v
}

// ===================== effect cases =====================

struct EffectCase {
    name: &'static str,
    setup: Vec<(&'static str, i64)>,
    effects: Vec<E>,
    arsenal: Vec<u16>,
    /// Emit `weapon_damage_mult` over the WHOLE catalog. Only the handful of cases
    /// that actually move a per-type / per-scope additive need it; for the rest it
    /// would be 86 copies of the same number per case.
    all_weapons: bool,
    /// Weapon def whose `on_hit` is pushed through `scale_on_hit`.
    on_hit_def: u16,
}

#[allow(clippy::too_many_arguments)]
fn c(
    name: &'static str,
    setup: Vec<(&'static str, i64)>,
    effects: Vec<E>,
    arsenal: Vec<u16>,
    all_weapons: bool,
    on_hit_def: u16,
) -> EffectCase {
    EffectCase { name, setup, effects, arsenal, all_weapons, on_hit_def }
}

/// The case table. INPUTS only — every expectation is computed from them by
/// [`effect_cases`] below.
fn effect_case_table() -> Vec<EffectCase> {
    vec![
        c("identity", vec![], vec![], vec![], true, 0),
        c("all_tags", vec![], vec![E::DamageGlobalPct(7, 100), E::DamageTypePct(3u8, 13, 100), E::DamageMulPct(1, 3), E::AttackSpeedPct(17, 100), E::BountyPct(35, 100), E::IncomeFlat(23), E::MaxHp(1700), E::Armor(9), E::ManaShield(1234, 7), E::HpRegen(11), E::Dodge(23u32), E::DamageScopePct(4u8, 19, 100), E::SpikesFlat(31), E::SpikesPct(41, 100), E::GrantVulnPulse(1, 2, 3), E::HealOnKill(13), E::HealOnPoison(3), E::IncomePct(29, 100), E::IncomeRegenPct(7, 100), E::BountyProc(5, 200), E::DamageVsStunnedPct(21, 100), E::DamageVsPoisonedPct(23, 100), E::PoisonDamagePct(37, 100), E::StunDurationPct(43, 100), E::GrantDuplicator(1, 2), E::GrantVoucher(3), E::GrantGold(400), E::HealingPct(27, 100), E::MissingHpHealPct(3, 100), E::GrantRevive(1500), E::DamagePerWeapon(10, 4, 11), E::TradeMaxHpForGold(100, 200), E::TradeRegenForGold(3, 400), E::GoldPerDamagePct(3, 1000), E::IncomeShieldPct(9, 100), E::MaxHpPct(25, 100), E::HpRegenPct(25, 100), E::ManaRegenPct(25, 100), E::ShieldActiveDrPct(15, 100), E::HealOnDamaged(45), E::DamagePerMaxHp(1, 100), E::DamagePerBountyPct(1, 100), E::ShieldActiveDamagePct(20, 100), E::ManaOnKill(17), E::ShieldBreakStun(1200, 15), E::SpikesPoison(2, 90), E::StackingSpikes(20, 25), E::DamageAura(600, 30, 200)], vec![], true, 0),
        c("additive_within_kind", vec![], vec![E::DamageGlobalPct(1, 4), E::DamageGlobalPct(1, 4)], vec![], false, 0),
        c("additive_inexact_thrice", vec![], vec![E::DamageGlobalPct(1, 10), E::DamageGlobalPct(1, 10), E::DamageGlobalPct(1, 10)], vec![], false, 0),
        c("mult_across_sources", vec![], vec![E::DamageGlobalPct(1, 1), E::DamageMulPct(1, 1)], vec![], false, 0),
        c("mult_then_add", vec![], vec![E::DamageMulPct(1, 1), E::DamageGlobalPct(1, 1)], vec![], false, 0),
        c("mul_order_a", vec![], vec![E::DamageMulPct(1, 3), E::DamageMulPct(1, 7)], vec![], false, 0),
        c("mul_order_b", vec![], vec![E::DamageMulPct(1, 7), E::DamageMulPct(1, 3)], vec![], false, 0),
        c("mul_chain_five", vec![], vec![E::DamageMulPct(1, 3), E::DamageMulPct(1, 7), E::DamageMulPct(2, 9), E::DamageMulPct(1, 11), E::DamageMulPct(5, 13)], vec![], true, 0),
        c("additive_and_mult_mixed", vec![], vec![E::DamageGlobalPct(1, 10), E::DamageTypePct(2u8, 1, 5), E::DamageScopePct(0u8, 25, 100), E::DamageScopePct(6u8, 25, 100), E::DamageScopePct(8u8, 25, 100), E::DamageMulPct(1, 4), E::DamageMulPct(1, 4)], vec![], true, 0),
        c("all_types", vec![], vec![E::DamageTypePct(0u8, 1, 100), E::DamageTypePct(1u8, 2, 100), E::DamageTypePct(2u8, 3, 100), E::DamageTypePct(3u8, 4, 100), E::DamageTypePct(4u8, 5, 100)], vec![], true, 0),
        c("all_scopes", vec![], vec![E::DamageScopePct(0u8, 1, 100), E::DamageScopePct(1u8, 2, 100), E::DamageScopePct(2u8, 3, 100), E::DamageScopePct(3u8, 4, 100), E::DamageScopePct(4u8, 5, 100), E::DamageScopePct(5u8, 6, 100), E::DamageScopePct(6u8, 7, 100), E::DamageScopePct(7u8, 8, 100), E::DamageScopePct(8u8, 9, 100), E::DamageScopePct(9u8, 10, 100), E::DamageScopePct(10u8, 11, 100), E::DamageScopePct(11u8, 12, 100)], vec![], true, 0),
        c("scope_modulo_wrap", vec![], vec![E::DamageScopePct(14u8, 50, 100), E::DamageTypePct(7u8, 50, 100)], vec![], true, 0),
        c("maxhp_flat_then_pct", vec![], vec![E::MaxHp(1000), E::MaxHpPct(25, 100)], vec![], false, 0),
        c("maxhp_pct_then_flat", vec![], vec![E::MaxHpPct(25, 100), E::MaxHp(1000)], vec![], false, 0),
        c("maxhp_pct_compounds", vec![], vec![E::MaxHpPct(25, 100), E::MaxHpPct(25, 100), E::MaxHpPct(25, 100), E::MaxHpPct(25, 100)], vec![], false, 0),
        c("hpregen_pct_compounds", vec![], vec![E::HpRegen(10), E::HpRegenPct(25, 100), E::HpRegenPct(25, 100), E::HpRegenPct(25, 100)], vec![], false, 0),
        c("hpregen_pct_on_zero", vec![], vec![E::HpRegenPct(25, 100), E::HpRegen(10)], vec![], false, 0),
        c("hpregen_pct_on_negative", vec![], vec![E::HpRegen(-40), E::HpRegenPct(25, 100), E::HpRegenPct(25, 100)], vec![], false, 0),
        c("manaregen_pct_compounds", vec![], vec![E::ManaShield(100, 8), E::ManaRegenPct(25, 100), E::ManaRegenPct(25, 100)], vec![], false, 0),
        c("dodge_cap", vec![], vec![E::Dodge(50u32), E::Dodge(50u32), E::Dodge(50u32)], vec![], false, 0),
        c("dodge_below_cap", vec![], vec![E::Dodge(11u32), E::Dodge(22u32)], vec![], false, 0),
        c("revive_max_bonus", vec![], vec![E::GrantRevive(1000), E::GrantRevive(3000), E::GrantRevive(2000)], vec![], false, 0),
        c("spikes_poison_keeps_stronger", vec![], vec![E::SpikesPoison(5, 10), E::SpikesPoison(2, 90), E::SpikesPoison(1, 10)], vec![], false, 0),
        c("spikes_poison_ties_replace", vec![], vec![E::SpikesPoison(3, 30), E::SpikesPoison(9, 10)], vec![], false, 0),
        c("stacking_spikes_twice", vec![], vec![E::StackingSpikes(20, 25), E::StackingSpikes(5, 40)], vec![], false, 0),
        c("shieldbreak_twice", vec![], vec![E::ShieldBreakStun(600, 30), E::ShieldBreakStun(1200, 15)], vec![], false, 0),
        c("aura_twice", vec![], vec![E::DamageAura(600, 30, 200), E::DamageAura(900, 45, 100)], vec![], false, 0),
        c("aura_then_narrow", vec![], vec![E::DamageAura(900, 45, 100), E::DamageAura(600, 30, 200)], vec![], false, 0),
        c("poison_and_stun_flavor", vec![], vec![E::PoisonDamagePct(50, 100), E::StunDurationPct(30, 100)], vec![], false, 0),
        c("meta_effects_are_noops", vec![], vec![E::GrantVulnPulse(1, 2, 3), E::GrantDuplicator(1, 2), E::GrantVoucher(3), E::GrantGold(400), E::TradeMaxHpForGold(1, 2), E::TradeRegenForGold(3, 4)], vec![], false, 0),
        c("dyn_maxhp", vec![], vec![E::DamagePerMaxHp(1, 100), E::MaxHp(5000)], vec![], false, 0),
        c("dyn_maxhp_then_more_hp", vec![], vec![E::DamagePerMaxHp(1, 100), E::MaxHp(5000), E::MaxHp(20000)], vec![], false, 0),
        c("dyn_bounty", vec![], vec![E::DamagePerBountyPct(1, 100), E::BountyPct(200, 100)], vec![], false, 0),
        c("dyn_bounty_below_base", vec![], vec![E::DamagePerBountyPct(1, 100), E::BountyPct(-50, 100)], vec![], false, 0),
        c("dyn_shield_up", vec![], vec![E::ShieldActiveDamagePct(20, 100), E::ManaShield(4000, 0)], vec![], false, 0),
        c("dyn_shield_none", vec![], vec![E::ShieldActiveDamagePct(20, 100)], vec![], false, 0),
        c("dyn_all_three", vec![], vec![E::DamagePerMaxHp(1, 100), E::DamagePerBountyPct(1, 100), E::ShieldActiveDamagePct(20, 100), E::MaxHp(7000), E::BountyPct(150, 100), E::ManaShield(2000, 3)], vec![], false, 0),
        c("economy_levers", vec![], vec![E::IncomeFlat(20), E::IncomePct(25, 100), E::IncomeRegenPct(1, 4), E::IncomeShieldPct(1, 4), E::GoldPerDamagePct(3, 1000), E::BountyPct(1, 2), E::BountyProc(5, 200), E::BountyProc(5, 200)], vec![], false, 0),
        c("maxhp_pct_overheal", vec![("hp", 40000)], vec![E::MaxHpPct(25, 100)], vec![], false, 0),
        c("maxhp_pct_hits_stat_ceil", vec![("max_hp", 999999999999)], vec![E::MaxHpPct(25, 100)], vec![], false, 0),
        c("hpregen_pct_hits_negative_ceil", vec![("hp_regen_per_tick", -999999999999)], vec![E::HpRegenPct(25, 100)], vec![], false, 0),
        c("manaregen_pct_hits_stat_ceil", vec![("mana_regen_per_tick", 999999999999)], vec![E::ManaRegenPct(25, 100)], vec![], false, 0),
        c("dodge_cap_wide_den", vec![("dodge_den", 10000)], vec![E::Dodge(9000u32)], vec![], false, 0),
        c("dodge_cap_odd_den", vec![("dodge_den", 33)], vec![E::Dodge(100u32)], vec![], false, 0),
        c("aura_cadence_min_from_seeded", vec![("aura_cadence", 12)], vec![E::DamageAura(300, 40, 50)], vec![], false, 0),
        c("self_scaling_death_engines", vec![], vec![E::DamagePerWeapon(10, 4, 10)], vec![10, 10, 10], false, 0),
        c("self_scaling_none_owned", vec![], vec![E::DamagePerWeapon(10, 4, 10)], vec![], false, 0),
        c("self_scaling_two_rules", vec![], vec![E::DamagePerWeapon(10, 4, 10), E::DamagePerWeapon(0, 1, 25), E::DamagePerWeapon(10, 4, 5)], vec![10, 0, 0, 10, 0], false, 0),
        c("on_hit_w3", vec![], vec![E::PoisonDamagePct(37, 100), E::StunDurationPct(43, 100)], vec![], false, 3),
        c("on_hit_identity_w3", vec![], vec![], vec![], false, 3),
        c("on_hit_w5", vec![], vec![E::PoisonDamagePct(37, 100), E::StunDurationPct(43, 100)], vec![], false, 5),
        c("on_hit_identity_w5", vec![], vec![], vec![], false, 5),
        c("on_hit_w75", vec![], vec![E::PoisonDamagePct(37, 100), E::StunDurationPct(43, 100)], vec![], false, 75),
        c("on_hit_identity_w75", vec![], vec![], vec![], false, 75),
        c("on_hit_w84", vec![], vec![E::PoisonDamagePct(37, 100), E::StunDurationPct(43, 100)], vec![], false, 84),
        c("on_hit_identity_w84", vec![], vec![], vec![], false, 84),
        c("softcap_maxhp_identity_below_knee", vec![("max_hp", 129999), ("hp", 0)], vec![E::MaxHp(1)], vec![], false, 0),
        c("softcap_maxhp_identity_far_below", vec![("max_hp", 24000), ("hp", 0)], vec![E::MaxHp(100000)], vec![], false, 0),
        c("softcap_maxhp_exactly_at_knee_full_value", vec![("max_hp", 130000), ("hp", 0)], vec![E::MaxHp(2000)], vec![], false, 0),
        c("softcap_maxhp_one_past_knee", vec![("max_hp", 130001), ("hp", 0)], vec![E::MaxHp(2000)], vec![], false, 0),
        c("softcap_maxhp_cubic_two_knees", vec![("max_hp", 260000), ("hp", 0)], vec![E::MaxHp(8000)], vec![], false, 0),
        c("softcap_maxhp_cubic_four_knees", vec![("max_hp", 520000), ("hp", 0)], vec![E::MaxHp(64000)], vec![], false, 0),
        c("softcap_maxhp_monotone_above_knee_a", vec![("max_hp", 260000), ("hp", 0)], vec![E::MaxHp(8000)], vec![], false, 0),
        c("softcap_maxhp_monotone_above_knee_b", vec![("max_hp", 260000), ("hp", 0)], vec![E::MaxHp(9000)], vec![], false, 0),
        c("softcap_maxhp_negative_inc_attenuated", vec![("max_hp", 260000), ("hp", 260000)], vec![E::MaxHp(-8000)], vec![], false, 0),
        c("softcap_maxhp_flat_hits_stat_ceil", vec![("max_hp", 130000), ("hp", 0)], vec![E::MaxHp(1000000000000)], vec![], false, 0),
        c("softcap_maxhp_flat_hits_negative_ceil", vec![("max_hp", 0), ("hp", 0)], vec![E::MaxHp(-2000000000000)], vec![], false, 0),
        c("softcap_maxhp_pct_hp_tracks_applied", vec![("max_hp", 300000), ("hp", 0)], vec![E::MaxHpPct(25, 100)], vec![], false, 0),
        c("softcap_maxhp_pct_at_knee", vec![("max_hp", 130000), ("hp", 0)], vec![E::MaxHpPct(25, 100)], vec![], false, 0),
        c("softcap_armor_identity_at_knee", vec![("armor", 1000)], vec![E::Armor(50)], vec![], false, 0),
        c("softcap_armor_above_knee", vec![("armor", 2000)], vec![E::Armor(8)], vec![], false, 0),
        c("softcap_armor_far_above_knee", vec![("armor", 17240)], vec![E::Armor(200)], vec![], false, 0),
        c("softcap_hp_regen_at_knee", vec![("hp_regen_per_tick", 16000)], vec![E::HpRegen(500)], vec![], false, 0),
        c("softcap_hp_regen_above_knee", vec![("hp_regen_per_tick", 32000)], vec![E::HpRegen(8000)], vec![], false, 0),
        c("softcap_hp_regen_pct_above_knee", vec![("hp_regen_per_tick", 284428)], vec![E::HpRegenPct(25, 100)], vec![], false, 0),
        c("softcap_mana_pool_and_regen_above_knees", vec![("mana_shield_max", 200000), ("mana_shield", 0), ("mana_regen_per_tick", 4000)], vec![E::ManaShield(8000, 8000)], vec![], false, 0),
        c("softcap_mana_regen_pct_above_knee", vec![("mana_regen_per_tick", 569275)], vec![E::ManaRegenPct(25, 100)], vec![], false, 0),
        c("softcap_mana_shield_identity_below_knee", vec![("mana_shield_max", 90000), ("mana_shield", 0), ("mana_regen_per_tick", 0)], vec![E::ManaShield(4000, 100)], vec![], false, 0),
        c("softcap_mul_nine_sources_below_knee", vec![], rep(E::DamageMulPct(1, 4), 9), vec![], false, 0),
        c("softcap_mul_twenty_sources_crosses_knee", vec![], rep(E::DamageMulPct(1, 4), 20), vec![], false, 0),
        c("softcap_mul_sixty_doublings_deep_tail", vec![], rep(E::DamageMulPct(1, 1), 60), vec![], false, 0),
        c("softcap_mul_two_hundred_fifty_quarters", vec![], rep(E::DamageMulPct(1, 4), 250), vec![], false, 0),
        c("softcap_maxhp_bundle_sixty_deep", vec![], maxhp_bundle(60), vec![], false, 0),
        // `INCOME_REGEN_SOFT` (`docs/11 §11.8`): the ×0.25 knee sits at ONE copy of
        // `Entangled Gold Mine` (+25% each), so copies one and two land at full value
        // and every copy after them decays cubically. 150 copies is the exact stack the
        // degeneracy pass measured — uncapped it would be ×37.5 of income healed per
        // tick. No other case in this table leaves the identity region, so without this
        // one the knee is not covered by the port's contract at all.
        c("softcap_income_regen_one_hundred_fifty_gold_mines", vec![], rep(E::IncomeRegenPct(25, 100), 150), vec![], false, 0),
        c("synergy_rides_self_scaling_with_rules", vec![], vec![E::DamagePerWeapon(10, 4, 10), E::DamagePerWeapon(0, 1, 25)], vec![8, 0, 2, 1, 4, 10, 10, 0], false, 0),
        c("synergy_magic_bolt_x14_scores_zero", vec![], vec![], vec![0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], false, 0),
    ]
}

fn effect_cases() -> Value {
    let mut out = Vec::new();
    for case in effect_case_table() {
        let mut s = ArenaState::new(1, 0);
        s.modifiers = Modifiers::new();
        for (k, v) in &case.setup {
            apply_setup(&mut s, k, *v);
        }
        for &e in &case.effects {
            s.modifiers.apply_effect(e, &mut s.economy, &mut s.tank);
        }
        let owned = arsenal(&case.arsenal);

        let damage_mult: Vec<Value> =
            (0..5u8).map(|t| hex(s.modifiers.damage_mult(t).raw())).collect();
        let weapon_damage_mult: Vec<Value> = if case.all_weapons {
            c::WEAPONS.iter().map(|w| hex(s.modifiers.weapon_damage_mult(w).raw())).collect()
        } else {
            Vec::new()
        };
        let self_scaling: Vec<Value> =
            (0..5u8).map(|t| hex(s.modifiers.self_scaling_add(t, &owned).raw())).collect();
        let oh = s.modifiers.scale_on_hit(c::WEAPONS[case.on_hit_def as usize].on_hit);

        out.push(obj(vec![
            ("name", Value::Str(case.name.to_string())),
            (
                "setup",
                Value::Arr(
                    case.setup
                        .iter()
                        .map(|(k, v)| obj(vec![("k", Value::Str(k.to_string())), ("v", int(*v))]))
                        .collect(),
                ),
            ),
            ("effects", Value::Arr(case.effects.iter().map(|e| words(e.words())).collect())),
            ("arsenal", ints(case.arsenal.iter().map(|&d| d as i64))),
            ("modifiers", modifiers_value(&s.modifiers)),
            ("economy", economy_value(&s.economy)),
            ("tank", tank_value(&s.tank)),
            (
                "queries",
                obj(vec![
                    ("damage_mult", Value::Arr(damage_mult)),
                    ("attack_speed_mult", hex(s.modifiers.attack_speed_mult().raw())),
                    (
                        "dynamic_global_add",
                        hex(s.modifiers.dynamic_global_add(&s.tank, &s.economy).raw()),
                    ),
                    ("weapon_damage_mult", Value::Arr(weapon_damage_mult)),
                    ("self_scaling_add", Value::Arr(self_scaling)),
                    ("arsenal_synergy_add", hex(Modifiers::arsenal_synergy_add(&owned).raw())),
                    (
                        "scale_on_hit",
                        obj(vec![
                            ("def", int(case.on_hit_def as i64)),
                            ("poison_dps", int(oh.poison_dps)),
                            ("poison_ticks", int(oh.poison_ticks as i64)),
                            ("frost_stacks", int(oh.frost_stacks as i64)),
                            ("fire_stacks", int(oh.fire_stacks as i64)),
                            ("stun_ticks", int(oh.stun_ticks as i64)),
                        ]),
                    ),
                ]),
            ),
        ]));
    }
    Value::Arr(out)
}

// ===================== synergy cases =====================

/// `Modifiers::arsenal_synergy_add` in isolation: a pure function of the owned
/// arsenal, so each case is just (arsenal → Fixed). Kept as its own array because
/// what is being pinned is a CAPS TABLE, whose interesting failures are all
/// off-by-one in a clamp — visible only by walking each axis a step at a time and
/// then past its cap.
fn synergy_case_table() -> Vec<(&'static str, Vec<u16>)> {
    vec![
        ("empty", vec![]),
        ("single_weapon", vec![0]),
        ("magic_bolt_x14", vec![0; 14]),
        ("magic_bolt_x86", vec![0; 86]),
        ("two_copies_two_defs", vec![10, 0, 0, 10, 0]),
        ("smoke_seed4_arsenal", vec![0, 16, 15]),
        ("one_per_damage_type_1", vec![8]),
        ("one_per_damage_type_2", vec![8, 0]),
        ("one_per_damage_type_3", vec![8, 0, 2]),
        ("one_per_damage_type_4", vec![8, 0, 2, 1]),
        ("one_per_damage_type_5", vec![8, 0, 2, 1, 4]),
        ("one_per_attack_class_1", vec![0]),
        ("one_per_attack_class_2", vec![0, 1]),
        ("one_per_attack_class_3", vec![0, 1, 6]),
        ("one_per_attack_class_4", vec![0, 1, 6, 7]),
        ("one_per_attack_class_5", vec![0, 1, 6, 7, 8]),
        ("one_per_attack_class_6", vec![0, 1, 6, 7, 8, 9]),
        ("first_1_defs", vec![0]),
        ("first_2_defs", vec![0, 1]),
        ("first_5_defs", vec![0, 1, 2, 3, 4]),
        ("first_8_defs", (0..8).collect()),
        ("first_9_defs", (0..9).collect()),
        ("first_10_defs", (0..10).collect()),
        ("first_12_defs", (0..12).collect()),
        ("first_20_defs", (0..20).collect()),
        ("first_30_defs", (0..30).collect()),
        ("first_60_defs", (0..60).collect()),
        ("first_86_defs", (0..86).collect()),
        ("last_ten_defs", vec![76, 77, 78, 79, 80, 81, 82, 83, 84, 85]),
        ("all_axes_max", vec![8, 0, 2, 1, 4, 0, 1, 6, 7, 8, 9]),
    ]
}

fn synergy_cases() -> Value {
    let mut out = Vec::new();
    for (name, defs) in synergy_case_table() {
        let owned = arsenal(&defs);
        // A FRESH aggregate (no `weapon_count_scaling` rules), so the synergy is the
        // first and only term in `self_scaling_add`.
        let m = Modifiers::new();
        out.push(obj(vec![
            ("name", Value::Str(name.to_string())),
            ("arsenal", ints(defs.iter().map(|&d| d as i64))),
            ("synergy", hex(Modifiers::arsenal_synergy_add(&owned).raw())),
            (
                "self_scaling_add",
                Value::Arr(
                    (0..5u8).map(|t| hex(m.self_scaling_add(t, &owned).raw())).collect::<Vec<_>>(),
                ),
            ),
        ]));
    }
    Value::Arr(out)
}

// ===================== ramp cases =====================

/// Catalog indices of the ramping modifiers the document covers — one per KIND of
/// ramp effect the port's `applyRamps` has to carry through: additive-global,
/// per-damage-type, flat income, bounty %, Max HP (which also grants HP regen via
/// `grant_pool_regen`, so a Max-HP ramp moves two stats per interval) and HP regen.
/// Indices, names and base effects all come from `content::MODIFIERS`, so a
/// rebalance flows through here on the next regeneration.
const RAMP_MODIFIERS: [u16; 6] = [16, 17, 18, 79, 80, 82];

/// Ticks at which `apply_ramps` is driven, in order: a tick before the interval,
/// exactly on it, twice on the same tick (idempotence), one after, the next two
/// intervals, and a multi-interval jump twice (the catch-up `while`).
const RAMP_TICKS: [u32; 9] = [0, 899, 900, 900, 901, 1800, 2700, 6300, 6300];

fn ramp_cases() -> Value {
    let mut out = Vec::new();
    for &idx in &RAMP_MODIFIERS {
        let def = &c::MODIFIERS[idx as usize];
        let spec = def.ramp.unwrap_or_else(|| {
            panic!("oracle: MODIFIERS[{idx}] ({}) carries no ramp", def.name)
        });

        let mut s = ArenaState::new(1, 0);
        s.modifiers = Modifiers::new();
        // The post-purchase snapshot: the modifier's BASE effects only, so the ramp
        // steps below isolate `apply_ramps` from the purchase path (which
        // `State`/`Shop` own and test separately).
        s.modifiers.apply(def, &mut s.economy, &mut s.tank);
        let pre = obj(vec![
            ("modifiers", modifiers_value(&s.modifiers)),
            ("economy", economy_value(&s.economy)),
            ("tank", tank_value(&s.tank)),
        ]);

        s.ramps = vec![ActiveRamp {
            effect: spec.effect,
            interval_ticks: spec.interval_ticks,
            next_apply: spec.interval_ticks,
        }];

        let mut steps = Vec::new();
        for &tick in &RAMP_TICKS {
            s.tick = tick;
            modifiers::apply_ramps(&mut s);
            steps.push(obj(vec![
                ("tick", int(tick as i64)),
                (
                    "ramps",
                    Value::Arr(
                        s.ramps
                            .iter()
                            .map(|r| {
                                obj(vec![
                                    ("next_apply", int(r.next_apply as i64)),
                                    ("interval_ticks", int(r.interval_ticks as i64)),
                                ])
                            })
                            .collect(),
                    ),
                ),
                ("modifiers", modifiers_value(&s.modifiers)),
                ("economy", economy_value(&s.economy)),
                ("tank", tank_value(&s.tank)),
            ]));
        }

        out.push(obj(vec![
            ("name", Value::Str(def.name.to_string())),
            ("modifier", int(idx as i64)),
            ("base_effects", Value::Arr(def.effects.iter().map(|e| words(e.words())).collect())),
            ("pre", pre),
            (
                "ramp",
                obj(vec![
                    ("effect", words(spec.effect.words())),
                    ("interval_ticks", int(spec.interval_ticks as i64)),
                    ("next_apply", int(spec.interval_ticks as i64)),
                ]),
            ),
            ("steps", Value::Arr(steps)),
        ]));
    }
    Value::Arr(out)
}

// ===================== economy cases =====================

struct EconCase {
    name: &'static str,
    seed: u64,
    setup: Vec<(&'static str, i64)>,
    fixed_setup: Vec<(&'static str, i64)>,
    pending_kills: Vec<u16>,
    ops: Vec<&'static str>,
}

fn ec(
    name: &'static str,
    seed: u64,
    setup: Vec<(&'static str, i64)>,
    fixed_setup: Vec<(&'static str, i64)>,
    pending_kills: Vec<u16>,
    ops: Vec<&'static str>,
) -> EconCase {
    EconCase { name, seed, setup, fixed_setup, pending_kills, ops }
}

/// The economy case table. INPUTS only. Seeds are fixed so the bounty-proc draws
/// are reproducible: the post-op `rng_proc` cursor is asserted after EVERY op, so
/// one extra or skipped `below` draw fails loudly (`roblox/SIM-SPEC.md` §S4).
fn econ_case_table() -> Vec<EconCase> {
    vec![
        ec("income_plain", 0x000000000000abcd, vec![("gold", 0), ("income_per_tick", 20)], vec![("bounty_mult", 0x00000000000a0000)], vec![], vec!["tick_income", "tick_income"]),
        ec("income_mult_quarter", 0x000000000000abcd, vec![("gold", 0), ("income_per_tick", 20)], vec![("income_mult", 0x0000000000014000)], vec![], vec!["tick_income", "tick_income"]),
        ec("income_mult_inexact", 0x0000000000000007, vec![("gold", 0), ("income_per_tick", 37)], vec![("income_mult", 0x0000000000015555)], vec![], vec!["tick_income", "tick_income", "tick_income"]),
        ec("income_regen_and_shield", 0x0000000000000003, vec![("gold", 0), ("income_per_tick", 100), ("max_hp", 1000), ("hp", 500), ("mana_shield", 0), ("mana_shield_max", 30)], vec![("income_regen_pct", 0x0000000000004000), ("income_shield_pct", 0x0000000000004000)], vec![], vec!["tick_income", "tick_income", "tick_income"]),
        ec("income_regen_scaled_by_healing_mult", 0x0000000000000003, vec![("gold", 0), ("income_per_tick", 100), ("max_hp", 100000), ("hp", 500)], vec![("income_regen_pct", 0x0000000000008000), ("healing_mult", 0x0000000000018000)], vec![], vec!["tick_income"]),
        ec("income_dead_no_heal", 0x0000000000000003, vec![("gold", 0), ("income_per_tick", 100), ("max_hp", 1000), ("hp", 10), ("dead", 1)], vec![("income_regen_pct", 0x0000000000004000), ("income_shield_pct", 0x0000000000004000)], vec![], vec!["tick_income"]),
        ec("bounty_drain_and_scale", 0x000000000000abcd, vec![("gold", 0)], vec![], vec![0, 1, 0], vec!["collect_bounties", "collect_bounties"]),
        ec("bounty_mult_three_halves", 0x000000000000abcd, vec![("gold", 0)], vec![("bounty_mult", 0x0000000000018000)], vec![1, 0, 3, 8], vec!["collect_bounties"]),
        ec("bounty_mult_half", 0x000000000000abcd, vec![("gold", 0)], vec![("bounty_mult", 0x0000000000008000)], vec![0, 3, 5, 11], vec!["collect_bounties"]),
        ec("bounty_mult_inexact", 0x000000000000abcd, vec![("gold", 0)], vec![("bounty_mult", 0x0000000000015555)], vec![0, 1, 3, 4, 5, 6, 7, 8, 9, 10, 11], vec!["collect_bounties"]),
        ec("bounty_no_proc_no_draw", 0x000000000000abcd, vec![("gold", 0)], vec![], vec![1, 1, 1, 1, 1], vec!["collect_bounties"]),
        ec("bounty_proc_always", 0x000000000000abcd, vec![("gold", 0), ("bounty_proc_chance_pct", 100)], vec![("bounty_proc_bonus", 0x0000000000020000)], vec![1], vec!["collect_bounties"]),
        ec("bounty_proc_always_with_mult", 0x000000000000abcd, vec![("gold", 0), ("bounty_proc_chance_pct", 100)], vec![("bounty_mult", 0x0000000000018000), ("bounty_proc_bonus", 0x0000000000020000)], vec![1, 0, 6], vec!["collect_bounties"]),
        ec("bounty_proc_half_with_inexact_mult", 0x0000000000001092, vec![("gold", 0), ("bounty_proc_chance_pct", 50)], vec![("bounty_mult", 0x0000000000015555), ("bounty_proc_bonus", 0x000000000000b333)], vec![1, 0, 3, 4, 5, 6, 7, 8, 9, 10, 11, 1, 1, 1], vec!["collect_bounties", "collect_bounties"]),
        ec("bounty_proc_half", 0x00000000000003e7, vec![("gold", 0), ("bounty_proc_chance_pct", 50)], vec![("bounty_proc_bonus", 0x0000000000020000)], vec![1, 1, 1, 1, 1, 0, 3, 6, 9, 11], vec!["collect_bounties", "collect_bounties"]),
        ec("bounty_proc_five_pct", 0x0000000000003039, vec![("gold", 0), ("bounty_proc_chance_pct", 5)], vec![("bounty_proc_bonus", 0x0000000000020000)], vec![1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], vec!["collect_bounties", "collect_bounties", "collect_bounties"]),
        ec("bounty_heal_and_mana_on_kill", 0x0000000000000005, vec![("gold", 0), ("max_hp", 1000), ("hp", 500), ("heal_on_kill", 15), ("mana_shield_max", 1000), ("mana_shield", 500), ("mana_on_kill", 15)], vec![], vec![0, 1, 0], vec!["collect_bounties", "collect_bounties", "collect_bounties"]),
        ec("bounty_on_kill_no_pool", 0x0000000000000005, vec![("gold", 0), ("mana_shield_max", 0), ("mana_shield", 0), ("mana_on_kill", 15)], vec![], vec![0], vec!["collect_bounties"]),
        ec("bounty_empty_is_noop", 0x0000000000000005, vec![("gold", 123)], vec![], vec![], vec!["collect_bounties"]),
        ec("bounty_dead_no_heal", 0x0000000000000005, vec![("gold", 0), ("max_hp", 1000), ("hp", 500), ("heal_on_kill", 15), ("dead", 1)], vec![], vec![0, 0], vec!["collect_bounties"]),
        ec("death_plain", 0x0000000000000005, vec![("tick", 42), ("hp", 0)], vec![], vec![], vec!["resolve_deaths"]),
        ec("death_revive_then_die", 0x0000000000000005, vec![("tick", 100), ("hp", -50), ("revives", 1), ("revive_bonus_hp", 2000)], vec![], vec![], vec!["resolve_deaths", "zero_hp", "resolve_deaths"]),
        ec("death_alive", 0x0000000000000005, vec![("hp", 1)], vec![], vec![], vec!["resolve_deaths"]),
        ec("round_start_is_noop", 0x0000000000000005, vec![], vec![], vec![], vec!["on_round_start"]),
        ec("income_then_bounty_scoreboard", 0x0000000000000005, vec![("gold", 0), ("income_per_tick", 20)], vec![], vec![1], vec!["tick_income", "collect_bounties"]),
        ec("income_regen_full_ramp", 0x0000000000000003, vec![("gold", 0), ("income_per_tick", 100), ("max_hp", 1000), ("hp", 500), ("tick", 54000)], vec![("income_regen_pct", 0x0000000000004000)], vec![], vec!["tick_income", "tick_income", "tick_income"]),
        ec("income_regen_full_ramp_scaled_by_healing_mult", 0x0000000000000003, vec![("gold", 0), ("income_per_tick", 100), ("max_hp", 100000), ("hp", 500), ("tick", 54000)], vec![("income_regen_pct", 0x0000000000008000), ("healing_mult", 0x0000000000018000)], vec![], vec!["tick_income"]),
        ec("income_regen_ceiling_early", 0x0000000000000003, vec![("gold", 0), ("income_per_tick", 1000000), ("max_hp", 24000), ("hp", 1000), ("tick", 3600)], vec![("income_regen_pct", 0x0000000000050000)], vec![], vec!["tick_income"]),
        ec("income_regen_ceiling_partial_ramp", 0x0000000000000003, vec![("gold", 0), ("income_per_tick", 1000000), ("max_hp", 24000), ("hp", 1000), ("tick", 20005)], vec![("income_regen_pct", 0x0000000000050000)], vec![], vec!["tick_income"]),
        ec("income_regen_ceiling_scaled_by_healing_mult", 0x0000000000000003, vec![("gold", 0), ("income_per_tick", 1000000), ("max_hp", 24000), ("hp", 1000), ("tick", 20005)], vec![("income_regen_pct", 0x0000000000050000), ("healing_mult", 0x0000000000018000)], vec![], vec!["tick_income"]),
    ]
}

fn econ_cases() -> Value {
    let mut out = Vec::new();
    for case in econ_case_table() {
        let mut s = ArenaState::new(case.seed, 0);
        s.modifiers = Modifiers::new();
        let rng_initial = s.rng_proc.state();
        for (k, v) in &case.setup {
            apply_setup(&mut s, k, *v);
        }
        for (k, v) in &case.fixed_setup {
            apply_fixed_setup(&mut s, k, Fixed::from_raw(*v));
        }
        s.total_gold_earned = 0;
        s.total_damage_dealt = 0;

        let mut steps = Vec::new();
        for op in &case.ops {
            match *op {
                "tick_income" => economy::tick_income(&mut s),
                "collect_bounties" => {
                    s.pending_kills = case.pending_kills.clone();
                    economy::collect_bounties(&mut s);
                }
                "resolve_deaths" => economy::resolve_deaths(&mut s),
                "on_round_start" => economy::on_round_start(&mut s),
                "zero_hp" => s.tank.hp = 0,
                other => panic!("oracle: unknown economy op {other:?}"),
            }
            steps.push(obj(vec![
                ("op", Value::Str(op.to_string())),
                (
                    "after",
                    obj(vec![
                        ("economy", economy_value(&s.economy)),
                        ("tank", tank_value(&s.tank)),
                        ("total_gold_earned", int(s.total_gold_earned)),
                        ("total_damage_dealt", int(s.total_damage_dealt)),
                        // `pending_kills` must be empty at every tick boundary, so
                        // only its LENGTH is contractual.
                        ("pending_kills", int(s.pending_kills.len() as i64)),
                        ("dead", Value::Bool(s.dead)),
                        (
                            "death_tick",
                            match s.death_tick {
                                Some(t) => int(t as i64),
                                None => Value::Null,
                            },
                        ),
                        ("rng_proc", hex_u(s.rng_proc.state())),
                    ]),
                ),
            ]));
        }

        out.push(obj(vec![
            ("name", Value::Str(case.name.to_string())),
            ("seed", hex_u(case.seed)),
            ("rng_proc_initial", hex_u(rng_initial)),
            (
                "setup",
                Value::Arr(
                    case.setup
                        .iter()
                        .map(|(k, v)| obj(vec![("k", Value::Str(k.to_string())), ("v", int(*v))]))
                        .collect(),
                ),
            ),
            (
                "fixed_setup",
                Value::Arr(
                    case.fixed_setup
                        .iter()
                        .map(|(k, v)| obj(vec![("k", Value::Str(k.to_string())), ("v", hex(*v))]))
                        .collect(),
                ),
            ),
            ("pending_kills", ints(case.pending_kills.iter().map(|&d| d as i64))),
            (
                "ops",
                Value::Arr(case.ops.iter().map(|o| Value::Str(o.to_string())).collect()),
            ),
            ("steps", Value::Arr(steps)),
        ]));
    }
    Value::Arr(out)
}

// ===================== document =====================

/// The whole oracle document.
fn oracle_document() -> Value {
    obj(vec![
        ("schema_version", int(SCHEMA_VERSION)),
        // ASSERTED by the Luau against `Content.CONTENT_HASH`: a regenerated catalog
        // must fail there loudly rather than assert the port against a fossil.
        ("content_hash", Value::Str(format!("{:016x}", super::content_hash()))),
        ("num_scopes", int(c::NUM_SCOPES as i64)),
        ("death_engine", int(c::DEATH_ENGINE as i64)),
        ("ramp_per_round", int(c::RAMP_PER_ROUND as i64)),
        ("effect_cases", effect_cases()),
        ("synergy_cases", synergy_cases()),
        ("ramp_cases", ramp_cases()),
        ("econ_cases", econ_cases()),
    ])
}

/// The oracle document as one line of canonical JSON — the single public entry
/// point of this module. Deterministic: two calls return identical bytes.
pub fn oracle_json() -> String {
    oracle_document().canonical()
}

/// `oracle_json()` wrapped as a Luau ModuleScript returning the raw text, the way
/// `export::content_data_luau` wraps `content.json`. Standalone Luau has no file
/// I/O, so `modifiers_test.luau` cannot read a `.json` — the document has to arrive
/// as a module. Generating that module (rather than pasting the JSON into the test)
/// is what stops it going stale: it already did once, and cost ten red assertions.
pub fn oracle_data_luau() -> String {
    let json = oracle_json();
    assert!(!json.contains("]==]"), "the oracle would break the Luau long-bracket literal");
    format!(
        "--!nonstrict\n\
         -- GENERATED by `cargo run -p sim --bin export-oracle` -- DO NOT EDIT.\n\
         -- Source of truth: sim-core/crates/sim/src/export/oracle.rs\n\
         -- Consumed by roblox/test/modifiers_test.luau (`roblox/CONTRACTS.md` C4).\n\
         return [==[\n{json}]==]\n"
    )
}

/// Repo-relative path of the generated artifact.
pub const ORACLE_OUTPUT: &str = "roblox/test/OracleData.luau";

#[cfg(test)]
mod tests {
    use super::*;

    /// Determinism, the same rule the other exporters hold: two runs, one answer.
    #[test]
    fn generation_is_byte_stable() {
        assert_eq!(oracle_json(), oracle_json());
    }

    /// The parser rejects any number carrying a `.`/`e`, so a successful reparse IS
    /// the "no floats anywhere" proof (C1) — and it also proves the document the
    /// Luau `Json.decode` sees is well-formed.
    #[test]
    fn document_reparses_with_no_floats() {
        let doc = Value::parse(&oracle_json()).expect("oracle document parses");
        assert_eq!(doc.at("schema_version").as_i64(), SCHEMA_VERSION);
        assert_eq!(doc.at("num_scopes").as_i64(), c::NUM_SCOPES as i64);
        assert!(!doc.at("effect_cases").as_arr().is_empty());
        assert!(!doc.at("synergy_cases").as_arr().is_empty());
        assert_eq!(doc.at("ramp_cases").as_arr().len(), RAMP_MODIFIERS.len());
        assert!(!doc.at("econ_cases").as_arr().is_empty());
    }

    /// Case names are the Luau's assertion tags; a duplicate makes a failure
    /// ambiguous and a rename silently drops coverage.
    #[test]
    fn case_names_are_unique() {
        for (what, names) in [
            ("effect", effect_case_table().iter().map(|c| c.name).collect::<Vec<_>>()),
            ("synergy", synergy_case_table().iter().map(|c| c.0).collect::<Vec<_>>()),
            ("econ", econ_case_table().iter().map(|c| c.name).collect::<Vec<_>>()),
        ] {
            let mut sorted = names.clone();
            sorted.sort_unstable();
            sorted.dedup();
            assert_eq!(sorted.len(), names.len(), "duplicate {what} case name");
        }
    }

    /// Every ramp case must name a modifier that actually ramps — otherwise the
    /// case silently degenerates into "apply_ramps on an empty list".
    #[test]
    fn every_ramp_case_modifier_ramps() {
        for &i in &RAMP_MODIFIERS {
            assert!(
                c::MODIFIERS[i as usize].ramp.is_some(),
                "MODIFIERS[{i}] ({}) no longer ramps",
                c::MODIFIERS[i as usize].name
            );
        }
    }

    /// `INCOME_REGEN_SOFT` coverage, as a property rather than a magic number: the
    /// deep `IncomeRegenPct` stack must land STRICTLY BELOW what an uncapped
    /// (linear) stack of the same copies would give. Without the knee the two are
    /// equal, so this fails if the soft cap is ever removed from that arm.
    #[test]
    fn the_income_regen_case_actually_crosses_its_knee() {
        let case = effect_case_table()
            .into_iter()
            .find(|c| c.name == "softcap_income_regen_one_hundred_fifty_gold_mines")
            .expect("the INCOME_REGEN_SOFT case is present");
        let mut s = ArenaState::new(1, 0);
        s.modifiers = Modifiers::new();
        let mut linear = Fixed::ZERO;
        for &e in &case.effects {
            s.modifiers.apply_effect(e, &mut s.economy, &mut s.tank);
            if let E::IncomeRegenPct(n, d) = e {
                linear += Fixed::from_ratio(n, d);
            }
        }
        assert!(
            s.economy.income_regen_pct < linear,
            "stack ({:?}) did not cross the knee (linear would be {:?})",
            s.economy.income_regen_pct,
            linear
        );
    }
}
